CREATE TABLE [dbo].[TeamLike]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [UserId] INT NOT NULL,
    [TeamId] INT NOT NULL,
    [IsLike] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [FK_TeamLikes_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User]([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_TeamLikes_Team] FOREIGN KEY ([TeamId]) REFERENCES [dbo].[Team]([Id]) ON DELETE CASCADE
);
