name: .NET

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: trailblazers-api
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install SSDT
      shell: powershell
      run: |
        $client = New-Object System.Net.WebClient
        $client.DownloadFile("https://aka.ms/vs/16/release/DataStorage2019.exe", "DataStorage2019.exe")
        Start-Process -FilePath "DataStorage2019.exe" -ArgumentList "/install", "/quiet", "/norestart" -Wait
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      run: dotnet test --no-build --verbosity normal
